[workspace]
resolver = "2"
members = [
    "wasm-frontend",
    "wasm-auth-backend",
    "wasm-general-backend",
    "shared/models",
    "shared/config",
]

[profile.dev]
overflow-checks = false



[patch.crates-io]
ahash = { path = "./ahash_fork" }
tempfile = { path = "./tempfile_fork" }

