version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wasm-frontend/dist:/home/ubuntu/pema-platform-rust/wasm-frontend/dist:ro
      - ./wasm-auth-backend/pkg:/home/ubuntu/pema-platform-rust/wasm-auth-backend/pkg:ro
      - ./wasm-general-backend/pkg:/home/ubuntu/pema-platform-rust/wasm-general-backend/pkg:ro
    depends_on:
      - wasm_auth_backend_builder
      - wasm_general_backend_builder

  wasm_auth_backend_builder:
    build:
      context: ./wasm-auth-backend
      dockerfile: Dockerfile
    volumes:
      - ./wasm-auth-backend/pkg:/pkg

  wasm_general_backend_builder:
    build:
      context: ./wasm-general-backend
      dockerfile: Dockerfile
    volumes:
      - ./wasm-general-backend/pkg:/pkg

