[package]
name = "ahash"
version = "0.8.6"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"], optional = true }

[features]
default = ["std"]
std = []

[target.'wasm32-unknown-unknown'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
